project:
  type: website
  output-dir: docs

website:
  title: "The Art of Communicating with Data"
  site-url: https://etc5523-2025.github.io/assignment-3-creating-a-blog-kkapoormails
  navbar:
    background: dark
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Blog"
        href: posts/
    right:
      - icon: github
        href: https://github.com/kkapoormails
        aria-label: "GitHub"
      - icon: linkedin
        href: https://au.linkedin.com/in/kkapoormails
        aria-label: "LinkedIn"
      - icon: envelope
        href: mailto:kkap0011@student.monash.edu
        aria-label: "Email"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
