project:
  type: website
  output-dir: docs

website:
  title: "Kunal Kapoor | Communicating with Data"
  navbar:
    right:
      - icon: github
        aria-label: GitHub
        href: "https://github.com/ETC5523-2025/assignment-3-creating-a-blog-kkapoormails"
  page-navigation: true
  search: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    link-external-newwindow: true

execute:
  freeze: auto